version: '3.8'

services:
  web:
    build: .
    ports:
      - "5012:5012"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/film_db
    volumes:
      - .:/app
      - ./static/uploads:/app/static/uploads

  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
